-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 13:29:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema teltonika
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `teltonika` ;

-- -----------------------------------------------------
-- Schema teltonika
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teltonika` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `teltonika` ;

-- -----------------------------------------------------
-- Table `teltonika`.`beacons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`beacons` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`beacons` (
  `id` VARCHAR(50) NOT NULL,
  `lugar` VARCHAR(255) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`beacons_detection_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`beacons_detection_status` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`beacons_detection_status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status_timestamp` TIMESTAMP NOT NULL,
  `Sector_1` ENUM('Negro', 'Rojo', 'Amarillo', 'Verde') NOT NULL DEFAULT 'Negro',
  `Sector_2` ENUM('Negro', 'Rojo', 'Amarillo', 'Verde') NOT NULL DEFAULT 'Negro',
  `Sector_3` ENUM('Negro', 'Rojo', 'Amarillo', 'Verde') NOT NULL DEFAULT 'Negro',
  `Sector_4` ENUM('Negro', 'Rojo', 'Amarillo', 'Verde') NOT NULL DEFAULT 'Negro',
  `Sector_5` ENUM('Negro', 'Rojo', 'Amarillo', 'Verde') NOT NULL DEFAULT 'Negro',
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`sectores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`sectores` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`sectores` (
  `id` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`configuracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`configuracion` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`configuracion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `beacon_id` VARCHAR(255) NULL DEFAULT NULL,
  `min_tiempo_permanencia` INT NULL DEFAULT NULL,
  `max_tiempo_permanencia` INT NULL DEFAULT NULL,
  `umbral_verde` INT NULL DEFAULT NULL,
  `umbral_amarillo` INT NULL DEFAULT NULL,
  `umbral_rojo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `beacon_id` (`beacon_id` ASC) VISIBLE,
  CONSTRAINT `configuracion_ibfk_1`
    FOREIGN KEY (`beacon_id`)
    REFERENCES `teltonika`.`sectores` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`debug_beacon_count`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`debug_beacon_count` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`debug_beacon_count` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sector` VARCHAR(20) NULL DEFAULT NULL,
  `beacon_id` VARCHAR(45) NULL DEFAULT NULL,
  `count` INT NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`devices` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`devices` (
  `id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `device_asignado` CHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`gps_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`gps_data` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`gps_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` BIGINT NULL DEFAULT NULL,
  `device_name` VARCHAR(255) NULL DEFAULT NULL,
  `device_type_id` INT NULL DEFAULT NULL,
  `event_enum` INT NULL DEFAULT NULL,
  `event_priority_enum` INT NULL DEFAULT NULL,
  `ident` VARCHAR(255) NULL DEFAULT NULL,
  `peer` VARCHAR(255) NULL DEFAULT NULL,
  `altitude` DECIMAL(10,2) NULL DEFAULT NULL,
  `direction` DECIMAL(10,2) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,8) NULL DEFAULT NULL,
  `satellites` INT NULL DEFAULT NULL,
  `speed` DECIMAL(10,2) NULL DEFAULT NULL,
  `protocol_id` INT NULL DEFAULT NULL,
  `server_timestamp` BIGINT NULL DEFAULT NULL,
  `timestamp` BIGINT NULL DEFAULT NULL,
  `ble_beacons` TEXT NULL DEFAULT NULL,
  `channel_id` INT NULL DEFAULT NULL,
  `codec_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 56972
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`parametrizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`parametrizaciones` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`parametrizaciones` (
  `param_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_parametro` VARCHAR(100) NOT NULL,
  `minimo` INT NOT NULL,
  `maximo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`param_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de parametros de sistema';


-- -----------------------------------------------------
-- Table `teltonika`.`parametro_color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`parametro_color` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`parametro_color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `umbral_min_verde` INT NOT NULL,
  `umbral_min_rojo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`umbrales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`umbrales` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`umbrales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `umbral_verde` INT NOT NULL,
  `umbral_amarillo` INT NOT NULL,
  `umbral_rojo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `teltonika`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teltonika`.`users` ;

CREATE TABLE IF NOT EXISTS `teltonika`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `resetToken` VARCHAR(255) NULL DEFAULT NULL,
  `resetTokenExpiry` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
